<a href="https://colab.research.google.com/github/IvanIri/Procesamiento-del-Habla/blob/main/TP_Semana1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Iván Irigoyen**

In [26]:
!pip install pymupdf pdfplumber nltk matplotlib pandas -q

In [27]:
import requests
import fitz  # PyMuPDF
import pdfplumber
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import re
import string
from collections import Counter

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [28]:
# Descarga de PDF

pdf_url = "https://www.imf.org/-/media/files/publications/weo/2023/october/spanish/text.pdf"
pdf_path = "text.pdf"

response = requests.get(pdf_url)
with open(pdf_path, "wb") as f:
  f.write(response.content)

print("PDF descargado exitosamente.")

PDF descargado exitosamente.

In [29]:
# Abrimos el documento

doc = fitz.open(pdf_path)

# Obtenemos los metadatos
metadata = doc.write
num_pag = doc.page_count

doc.metadata

{'format': 'PDF 1.6',
 'title': '',
 'author': '',
 'subject': '',
 'keywords': '',
 'creator': 'Adobe InDesign 19.0 (Macintosh)',
 'producer': 'Adobe PDF Library 17.0',
 'creationDate': "D:20231205233201+01'00'",
 'modDate': "D:20231205233310+01'00'",
 'trapped': '',
 'encryption': None}

Vemos mucha información faltantes con este analisis preliminar de los metadatos.

Solo obtenemos el formato "PDF 1.6", que fue hecho en "Adobe 19.0" y sus fechas de creación y actualización.

In [30]:
# Extraemos el texto crudo de las primeras 5 paginas.

texto_pag = []

for i in range(min(5, doc.page_count)):
  pag = doc.load_page(i)
  texto = pag.get_text("text")

  texto_pag.append(texto)

  print(f"\n{'='*40}")
  print(f"PAGINA {i+1}")
  print(f"{'='}*\n")
  print(texto[0:3000]) # le doy un maximo de caracteres a la salida.

========================================
PAGINA 1
=*

PERSPECTIVAS
DE LA ECONOMÍA
MUNDIAL
OCT
2023
Abordar las divergencias mundiales
FONDO MONETARIO INTERNACIONAL


========================================
PAGINA 2
=*

PERSPECTIVAS
DE LA ECONOMÍA
MUNDIAL
Abordar las divergencias mundiales
OCT
2023
FONDO MONETARIO INTERNACIONAL


========================================
PAGINA 3
=*

©2023 International Monetary Fund
Edición en español ©2023 Fondo Monetario Internacional

Edición en inglés
Portada y diseño: División de Soluciones Creativas, CSF, FMI
Composición: Absolute Service, Inc.; y AGS, una firma de RR Donnelley Company
Edición en español
Sección de Español y Portugués
Servicios Lingüísticos del FMI
Departamento de Servicios Corporativos e Instalaciones del FMI

Cataloging-in-Publication Data
IMF Library
Names: International Monetary Fund.
Title: World economic outlook (International Monetary Fund)
Other titles: WEO | Occasional paper (International Monetary Fund) | World economic and
financial surveys.
Description: Washington, DC : International Monetary Fund, 1980- | Semiannual | Some
issues also have thematic titles. | Began with issue for May 1980. | 1981-1984: Occasional
paper / International Monetary Fund, 0251-6365 | 1986-: World economic and financial
surveys, 0256-6877.
Identifiers: ISSN 0256-6877 (print) | ISSN 1564-5215 (online)
Subjects: LCSH: Economic development—Periodicals. | International economic relations—
Periodicals. | Debts, External—Periodicals. | Balance of payments—Periodicals. |
International finance—Periodicals. | Economic forecasting—Periodicals.
Classification: LCC HC10.W79
HC10.80
ISBN 979-8-40024-836-8 (edición impresa)

979-8-40024-839-9 (edición digital)
Descargo de responsabilidad: El informe Perspectivas de la economía mundial (informe
WEO, por su sigla en inglés) es un estudio elaborado por el personal técnico del FMI
que se publica dos veces al año, en el segundo y cuarto trimestre. El informe WEO se ha
enriquecido con sugerencias y comentarios de los directores ejecutivos, que debatieron
este informe el 26 de septiembre de 2023. Las opiniones expresadas en este informe son
las del personal técnico del FMI y no representan necesariamente las opiniones de los
directores ejecutivos del FMI o de las autoridades nacionales.
Cita recomendada: Fondo Monetario internacional. 2023. Perspectivas de la economía
mundial: Abordar las divergencias mundiales. Washington, DC (octubre).
La publicación puede adquirirse en línea, por fax o por correo:
International Monetary Fund, Publication Services
P.O. Box 92780, Washington, DC 20090, USA
Tel.: (202) 623-7430 Fax: (202) 623-7201
Correo electrónico: publications@imf.org
www.bookstore.imf.org
www.elibrary.imf.org


========================================
PAGINA 4
=*


Fondo Monetario Internacional | Octubre de 2023
iii
ÍNDICE
Supuestos y convenciones
viii
Información adicional
x
Datos
xi
Prefacio
xii
Introducción
xiii
Resumen ejecutivo
xvi
Capítulo 1. Perspectivas y políticas mundiales
1
Aumento de las divergencias mundiales
1
Perspectivas: Crecimiento estable pero lento
11
Riesgo de deterioro de las perspectivas, pero más equilibrado
22
Prioridades de política económica: De la desinflación al crecimiento sostenido
26
Recuadro 1.1. Debilitamiento de las perspectivas de crecimiento: Se alarga el camino
hacia la convergencia
31
Recuadro 1.2. Evaluación de riesgos en torno a las proyecciones de base de las
Perspectivas de la economía mundial
35
Sección especial sobre materias primas: La evolución de los mercados y el canal
de precios de las materias primas de la política monetaria
40
Referencias
54
Capítulo 2. Gestionar las expectativas: Inflación y política monetaria
57
Introducción
57
Patrones recientes de las expectativas inflacionarias
61
La incidencia de las expectativas en la dinámica inflacionaria
64
Formación de expectativas y formulación de la política monetaria
67
Conclusiones
74
Recuadro 2.1. Expectativas inflacionarias, atención y eficacia de la política monetaria
en el ámbito empresarial
76
Recuadro 2.2. Imprudencia fiscal y expectativas de inflación: El papel de los marcos
de política monetaria
78
Recuadro 2.3. Subsidios a la energía, inflación y expectativas inflacionarias: Un análisis
de las medidas de la zona del euro
80
Referencias
82
Capítulo 3. Fragmentación y mercados de materias primas: Vulnerabilidades y riesgos
85
Introducción
85
¿A qué atribuir la vulnerabilidad de los mercados de materias primas en caso
de fragmentación?
88
Fragmentación de los mercados de materias primas
91
¿Qué materias primas son las más vulnerables?
92
Efectos económicos de la fragmentación de los mercados de materias primas
95
Implicaciones para la transición hacia energías limpias
98


========================================
PAGINA 5
=*

PERSPECTIVAS DE LA ECONOMÍA MUNDIAL: ABORDAR LAS DIVERGENCIAS MUNDIALES
iv
Fondo Monetario Internacional | Octubre de 2023
Resumen e implicaciones para las políticas
100
Recuadro 3.1. Tensiones en el comercio internacional de materias primas:
Observaciones derivadas de los datos sobre buques cisterna
103
Recuadro 3.2. La fragmentación de los mercados de materias primas
con una óptica histórica: Muchos matices de gris
104
Recuadro 3.3. Variedad de los efectos económicos de la fragmentación
de los mercados de materias primas
105
Referencias
107
Apéndice estadístico
111
Supuestos
111
Novedades
111
Datos y convenciones
112
Notas sobre los países
113
Clasificación de los países
115
Características generales y composición de los grupos que conforman
la clasificación del informe WEO
116
Cuadro A. Clasificación según los grupos utilizados en Perspectivas
de la economía mundial y la participación de cada grupo en el PIB agregado,
la exportación de bienes y servicios, y la población, 2022
117
Cuadro B. Economías avanzadas por subgrupos
118
Cuadro C. Unión Europea
118
Cuadro D. Economías de mercados emergentes y en desarrollo por regiones
y fuentes principales de ingresos de exportación
119
Cuadro E. Economías de mercados emergentes y en desarrollo por regiones, posición
externa neta, países pobres muy endeudados y clasificación por ingreso per cápita
120
Cuadro F. Economías con períodos excepcionales de declaración de datos
122
Cuadro G. Documentación sobre los datos fundamentales
123
Recuadro A1. Supuestos de política económica en que se basan las proyecciones
para algunas economías
133
Lista de cuadros
139
Producto (cuadros A1–A4)
140
Inflación (cuadros A5–A7)
147
Políticas financieras (cuadro A8)
152
Comercio exterior (cuadro A9)
153
Transacciones en cuenta corriente (cuadros A10–A12)
155
Balanza de pagos en cuenta corriente y financiamiento externo (cuadro A13)
162
Flujo de fondos (cuadros A14)
166
Escenario de referencia a mediano plazo (cuadro A15)
169
Temas seleccionados de Perspectivas de la economía mundial
171
Deliberaciones del Directorio Ejecutivo del FMI sobre las perspectivas, septiembre de 2023
181
Cuadros
Cuadro 1.1. Panorama de las proyecciones de Perspectivas de la economía mundial
14
Cuadro 1.2. Panorama de las proyecciones de Perspectivas de la economía mundial
según ponderaciones basadas en los tipos de cambio
16
Cuadro 1.SE.1 Respuesta promedio de los IPC
45

Obtuvimos las primeras 5 paginas, algúnas contienen mas texto que otras. En el caso de las primeras esto sucede por q son titulos o las paginas contienen imagenes. Luego viene un gran texto que es introducción o presentación. Y el resto de paginas son un indice de los temas que contiene el pdf.

In [31]:
# Analizamos los separadores

muestra = texto_pag[4]
print(repr(muestra))

'PERSPECTIVAS DE LA ECONOMÍA MUNDIAL: ABORDAR LAS DIVERGENCIAS MUNDIALES\niv\t\nFondo Monetario Internacional | Octubre de 2023\nResumen e implicaciones para las políticas\t\n100\nRecuadro 3.1. Tensiones en el comercio internacional de materias primas:  \nObservaciones derivadas de los datos sobre buques cisterna\t\n103\nRecuadro 3.2. La fragmentación de los mercados de materias primas  \ncon una óptica histórica: Muchos matices de gris\t\n104\nRecuadro 3.3. Variedad de los efectos económicos de la fragmentación  \nde los mercados de materias primas\t\n105\nReferencias\t\n107\nApéndice estadístico\t\n111\nSupuestos\t\n111\nNovedades\t\n111\nDatos y convenciones\t\n112\nNotas sobre los países\t\n113\nClasificación de los países\t\n115\nCaracterísticas generales y composición de los grupos que conforman  \nla clasificación del informe WEO\t\n116\nCuadro A. Clasificación según los grupos utilizados en Perspectivas  \nde la economía mundial y la participación de cada grupo en el PIB agregado,  \nla exportación de bienes y servicios, y la población, 2022\t\n117\nCuadro B. Economías avanzadas por subgrupos\t\n118\nCuadro C. Unión Europea\t\n118\nCuadro D. Economías de mercados emergentes y en desarrollo por regiones  \ny fuentes principales de ingresos de exportación\t\n119\nCuadro E. Economías de mercados emergentes y en desarrollo por regiones, posición  \nexterna neta, países pobres muy endeudados y clasificación por ingreso per cápita \t\n120\nCuadro F. Economías con períodos excepcionales de declaración de datos\t\n122\nCuadro G. Documentación sobre los datos fundamentales\t\n123\nRecuadro A1. Supuestos de política económica en que se basan las proyecciones  \npara algunas economías\t\n133\nLista de cuadros\t\n139\nProducto (cuadros A1–A4)\t\n140\nInflación (cuadros A5–A7)\t\n147\nPolíticas financieras (cuadro A8)\t\n152\nComercio exterior (cuadro A9)\t\n153\nTransacciones en cuenta corriente (cuadros A10–A12)\t\n155\nBalanza de pagos en cuenta corriente y financiamiento externo (cuadro A13)\t\n162\nFlujo de fondos (cuadros A14)\t\n166\nEscenario de referencia a mediano plazo (cuadro A15)\t\n169\nTemas seleccionados de Perspectivas de la economía mundial \t\n171\nDeliberaciones del Directorio Ejecutivo del FMI sobre las perspectivas, septiembre de 2023\t\n181\nCuadros\nCuadro 1.1. Panorama de las proyecciones de Perspectivas de la economía mundial\t\n14\nCuadro 1.2. Panorama de las proyecciones de Perspectivas de la economía mundial  \nsegún ponderaciones basadas en los tipos de cambio\t\n16\nCuadro 1.SE.1 Respuesta promedio de los IPC\t\n45\n'

Acá vemos que se utilizan los separadores "\n" y "\t" para los saltos de lineas.

Estos los vemos mucho por que justo estoy analizando las paginas que contienen los indices del documento. por lo que luego de cada titulo nos encontramos con un separador que hacen que el texto del indice este en forma de "lista".

No observo el uso de otros separadores.

In [32]:
# Extracción de datos tabulares

# pagina 33 contiene datos tabulares

with pdfplumber.open(pdf_path) as pdf:
  pag = pdf.pages[33]
  tablas = pag.extract_tables()

tabla = tablas[0]
df_tabla = pd.DataFrame(tabla)

df_tabla.head()

,0,1,2,3,4,5,6,7
0,Proyecciones,None,,Diferencia con la\nActualización del informe\n...,None,,Diferencia con\nel informe WEO\nde abril de 20231,None
1,2023,2024,None,2023,2024,None,2023,2024
2,"2,9","3,2",,"0,0","0,3",,"0,0","0,1"
3,"1,5","1,5",None,"0,1","0,1",None,"0,4","–0,1"
4,"1,9","1,4",None,"0,5","0,3",None,"0,9","0,1"

Me trajo la tabla, pero no completa, no logro identificar varios titulos de las columnas y no trajo ningúno de los de las filas.

Esto puede ser por que no es una tabla tipica la del documento, no tiene los limites de cada fila y columna bien definidos

In [33]:
# Intento 2 de extración de datos tabulares

with pdfplumber.open(pdf_path) as pdf:
  pag = pdf.pages[33]

  tablas = pag.extract_table({
      "vertical_strategy": "lines",
      "horizontal_strategy": "lines"
  })

df_tabla = pd.DataFrame(tablas)
df_tabla.head()

,0,1,2,3,4,5,6,7
0,Proyecciones,None,,Diferencia con la\nActualización del informe\n...,None,,Diferencia con\nel informe WEO\nde abril de 20231,None
1,2023,2024,None,2023,2024,None,2023,2024
2,"2,9","3,2",,"0,0","0,3",,"0,0","0,1"
3,"1,5","1,5",None,"0,1","0,1",None,"0,4","–0,1"
4,"1,9","1,4",None,"0,5","0,3",None,"0,9","0,1"

Probamos otra forma dandole más indicaciones de como esta formada la tabla, pero aún así no nos trae la información de la tabla completamente.

Al no tener un formato convencional la tabla del documento las extracciones de datos tabulares se dificulta. No alcanza con "pdfplumber" para su extracción

In [34]:
# Inteto 3 de extracción de datos tabulares.
# Ahora probamos Tabula

!pip install tabula-py

Requirement already satisfied: tabula-py in /usr/local/lib/python3.12/dist-packages (2.10.0)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.12/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)

In [35]:
import tabula

df_tablas = tabula.read_pdf(pdf_path, pages=33, multiple_tables=True)

for df in df_tablas:
    print(df.head(10))

            Unnamed: 0 Unnamed: 1    Unnamed: 2          Diferencia con la  \
0                  NaN        NaN           NaN  Actualización del informe
1                  NaN        NaN  Proyecciones      WEO de julio de 20231
2                  NaN       2022     2023 2024                  2023 2024
3     Producto mundial        3,5       3,0 2,9                   0,0 –0,1
4  Economías avanzadas        2,6       1,5 1,4                    0,0 0,0
5       Estados Unidos        2,1       2,1 1,5                    0,3 0,5
6        Zona del euro        3,3       0,7 1,2                  –0,2 –0,3
7             Alemania        1,8      –0,5 0,9                  –0,2 –0,4
8              Francia        2,5       1,0 1,3                    0,2 0,0
9              Italia2        3,7       0,7 0,7                  –0,4 –0,2

      Diferencia con
0     el informe WEO
1  de abril de 20231
2          2023 2024
3           0,2 –0,1
4            0,2 0,0
5            0,5 0,4
6          –0,1 –0,2
7          –0,4 –0,2
8            0,3 0,0
9           0,0 –0,1

Observamos que Tabula funciono muchisimo mejor. Trajo más información de las celdas y completo tanto los titulos de las columnas como los de las filas.

los valores "NaN" que se observan corresponden a espacios en blanco de la tabla.

Los "Unnamed" hacen referencia a celdas sin información también, solo que las etiqueto diferente. Supongo que interpreto que solo la 1ra fila era el titulo de las columnas, cuando lo son las primeras 3/4 filas.

In [36]:
# Limpieza de las tablas

df_tabla.columns = [
    str(col).replace('Unnamed', '-')
    for col in df_tabla.columns
]

df_tabla.head(10)

,0,1,2,3,4,5,6,7
0,Proyecciones,None,,Diferencia con la\nActualización del informe\n...,None,,Diferencia con\nel informe WEO\nde abril de 20231,None
1,2023,2024,None,2023,2024,None,2023,2024
2,"2,9","3,2",,"0,0","0,3",,"0,0","0,1"
3,"1,5","1,5",None,"0,1","0,1",None,"0,4","–0,1"
4,"1,9","1,4",None,"0,5","0,3",None,"0,9","0,1"
5,"0,7","1,4",None,"–0,5","–0,1",None,"0,0","–0,4"
6,"–0,2","1,7",None,"–0,7","0,2",None,"–0,4","–0,1"
7,"1,0","1,5",None,"0,1","–0,1",None,"0,2","0,1"
8,"0,3","1,2",None,"–0,6","0,1",None,"–0,1","0,1"
9,"1,6","2,0",None,"–0,2","–0,2",None,"0,3","–0,1"

En esta parte de limpieza buscaba eliminar los "Unnamed" y los "Nan" que aparecen. Estos aparecen en celdas vacias y en celdas que interpreta como titulo. probe de varias formas que fui eliminando, pero no logre que me mantenga toda la info, en todos los casos me elimina la 1ra columna que contiene en cada fila a que hace referencia los valores de esa fila.

**NPL Basico**

In [37]:
!pip install nltk -q

In [38]:
import nltk
import string
import matplotlib.pyplot as plt
from collections import Counter
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [39]:
# Chequeamos si la pagina tiene solo texto

pagina_narrativa = doc.load_page(83)
texto_narrativo = pagina_narrativa.get_text("text")

print(texto_narrativo[:2000])

65
CAPÍTULO 2
Gestionar las expectativas: Inflación y política monetaria
Fondo Monetario Internacional | Octubre de 2023
Las estimaciones de los coeficientes representan la
variación en la inflación asociada a un incremento
de una desviación estándar del indicador de las
expectativas indicado12. El primer hallazgo es que
las expectativas de inflación a largo plazo tienen un
poder de predicción menor que el de indicadores a
corto plazo. Las expectativas inflacionarias a cinco
años, tanto basadas en el mercado financiero como de
los profesionales que elaboran pronósticos, presentan
coeficientes estandarizados menores a los de otros
indicadores (gráfico 2.5, dos conjuntos inferiores de
cajas y flecos). Estos resultados se condicen con los
de estudios recientes que hallan que las expectativas
a largo plazo inciden menos en la inflación corriente
(Werning, 2022; Hajdini, 2023). En segundo lugar, se
observa una notable coherencia entre las expectativas
de inflación a corto plazo de los profesionales que
elaboran pronósticos, los mercados financieros y las
empresas (gráfico 2.5, tres cajas y flecos superiores).
Estos resultados implican que un incremento de una
desviación estándar de las expectativas se asocia a un
incremento de la inflación corriente equivalente a
0,7 desviaciones estándar13. Por último, el coeficiente
correspondiente a las expectativas a corto plazo de los
hogares se sitúa a medio camino entre las expectativas a
corto y a largo plazo de otros agentes.
A la vista de estos hallazgos, y fundamentalmente
debido a la mayor amplitud de la cobertura temporal
y de economías, la especificación de base de la curva
de Phillips híbrida se estima a partir de las expectativas
inflacionarias a corto plazo de profesionales que
elaboran pronósticos (gráfico 2.6). La relación estimada
indica que un incremento de 1 punto porcentual de
las expectativas a corto plazo se asocia a un aumento
de 1,1 puntos porcentuales de la inflación corriente

In [40]:
nltk.download('punkt_tab')

# Tokenización. Convertir el texto en minuscula

texto_narrativo = texto_narrativo.lower()
tokens = word_tokenize(texto_narrativo, language='spanish')

print(tokens[:50])

['65', 'capítulo', '2', 'gestionar', 'las', 'expectativas', ':', 'inflación', 'y', 'política', 'monetaria', 'fondo', 'monetario', 'internacional', '|', 'octubre', 'de', '2023', 'las', 'estimaciones', 'de', 'los', 'coeficientes', 'representan', 'la', 'variación', 'en', 'la', 'inflación', 'asociada', 'a', 'un', 'incremento', 'de', 'una', 'desviación', 'estándar', 'del', 'indicador', 'de', 'las', 'expectativas', 'indicado12', '.', 'el', 'primer', 'hallazgo', 'es', 'que', 'las']

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [41]:
# Limpieza. Eliminar las stopwords y signos de puntuación

stop_words = set(stopwords.words('spanish'))

tokens_limpios = [
    token for token in tokens
    if token not in stop_words
    and token not in string.punctuation
    and token.isalpha()
]

print(tokens_limpios[:50])

['capítulo', 'gestionar', 'expectativas', 'inflación', 'política', 'monetaria', 'fondo', 'monetario', 'internacional', 'octubre', 'estimaciones', 'coeficientes', 'representan', 'variación', 'inflación', 'asociada', 'incremento', 'desviación', 'estándar', 'indicador', 'expectativas', 'primer', 'hallazgo', 'expectativas', 'inflación', 'largo', 'plazo', 'poder', 'predicción', 'menor', 'indicadores', 'corto', 'plazo', 'expectativas', 'inflacionarias', 'cinco', 'años', 'basadas', 'mercado', 'financiero', 'profesionales', 'elaboran', 'pronósticos', 'presentan', 'coeficientes', 'estandarizados', 'menores', 'indicadores', 'gráfico', 'dos']

In [42]:
# Frecuencia de palabras

frecuencias = Counter(tokens_limpios)
top_15 = frecuencias.most_common(15)

print(top_15)

[('inflación', 24), ('expectativas', 23), ('economías', 14), ('plazo', 12), ('corto', 9), ('coeficientes', 8), ('mercados', 8), ('emergentes', 7), ('corriente', 6), ('menor', 5), ('rezagada', 5), ('octubre', 4), ('incremento', 4), ('largo', 4), ('inflacionarias', 4)]

In [43]:
# convertir en DataFrame para graficar

df_freq = pd.DataFrame(top_15, columns=['Palabra', 'Frecuencia'])

df_freq

           Palabra  Frecuencia
0        inflación          24
1     expectativas          23
2        economías          14
3            plazo          12
4            corto           9
5     coeficientes           8
6         mercados           8
7       emergentes           7
8        corriente           6
9            menor           5
10        rezagada           5
11         octubre           4
12      incremento           4
13           largo           4
14  inflacionarias           4

In [44]:
# Grafico de barras de las palabras más frecuentes

import plotly.express as px

fig = px.bar(
    df_freq,
    x='Palabra',
    y='Frecuencia',
    title='Top 15 palabras más frecuentes',
    labels={'Palabra': 'Palabras', 'Frecuencia': 'Frecuencia'},
    text='Frecuencia'
)

fig.update_layout(
    xaxis_tickangle=45
)

fig.show()

No me sugirio ninguna palabra considerada stopwords. Por lo que puedo asegurar que la limpieza de este tipo de palabras funciono muy bien.